### PR TITLE
T36 target info

### PR DESCRIPTION
**Pull request by zawata**
Introduces the ability to get a list of available targets from a file. 

May want to rename the function name for better indication of what it does.

to test: 
load bsp file into the `.main_file` property of a spyce object, then call `.get_objects()` the output should be a list of available targets. 

bsp files will be available on google_drive

### CODE REVIEW

**Comment by dlahtine** [comment]
I get the following error

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
AttributeError: 'spyce' object has no attribute 'get_objects'
```

**Comment by zawata** [comment]
are you sure you built it correctly? mine works. 

what are the commands you are running

**Comment by dlahtine** [comment]
Tested again, working properly. I must have botched the first test.

**Review by dlahtine — APPROVED** [review]
Tested again; working properly. I must have botched the first test.

**Pull request merged**
