### PR TITLE
T38 Python Binding

### PR DESCRIPTION
**Pull request by zawata**
Looks like I accidentally included David's commit. Shouldn't be an issue.

This includes the SPICE Toolkit for all supported platforms as well as a method to compile for linux, mac, and windows. 
This will require cmake being installed on the hosts system.
The command to build should be something like `cmake --build ./build --target all`

Provided the command succeeds, you should be able to find `./spyce/libspyce.so.

### CODE REVIEW

**Comment by zawata** [comment]
adding david because hes on linux too

**Comment by trevorforrey** [comment]
What command should we run inside of _spyce_ to test if it works?

**Comment by zawata** [comment]
open a python3 console in the root of the project. 
> from spyce import spyce
> s = spyce.spyce()

that should cover making sure the project built.

**Comment by zawata** [comment]
Added some commits. should compile and run on mac and linux. requires Boost, Boost Python, Python3.5+, and cmake 3.12+ the cmake file should report any errors. 
heres the command i use: `cmake --build ./build --target all`

still need to discuss the idea of building a Docker Image but I don't think it will be done this sprint.

**Comment by trevorforrey** [comment]
I believe that it builds on linux. Not building on my machine as we plan to switch to Docker.

**Review by trevorforrey — APPROVED** [review]

**Comment by zawata** [comment]
good enough  :+1:

**Pull request merged**
