### PR TITLE
Make model earth centric

### PR DESCRIPTION
**Pull request by trevorforrey**

### CODE REVIEW

**Comment by trevorforrey** [comment]
screen shot 2019-02-14 at 11 52 53 am

**Review by hdua1 — CHANGES_REQUESTED** [review]
Great work, Trevor! The sole purpose of this branch has been achieved, though I'd like to suggest some changes now that the camera position has been changed.

- `const moonOrbitRadius = 4;` can now be changed to 3. The approx. distance from earth is ~250K, we cannot change it to 2 or 2.5 because it starts orbiting inside the surface of earth. I tried with 3 and that should be the best option to wrap up the distancing part.

- This is more of a comment than a change request(if you've a better implementation then it'd be great) I'm not completely sure about the sizing. Here's a snapshot from my research doc:
image
We can't really make it 109:1:1/4 but changing to 5:4:1 would not suffice the requirements. We can bring this up with the sponsor in our next meeting.

- [x] Moon Orbit
- [x] Sun:Earth Size

**Comment by trevorforrey** [comment]
Having the orbit around 3 feels a little too close for me
screen shot 2019-02-14 at 1 31 51 pm
.

I realized that the moon's distance from earth is 100x that of its size. Having that ratio stay true makes the moon incredibly small, however, at 50x, I think it strikes a happy medium between realistic and still visible.

screen shot 2019-02-14 at 1 22 44 pm

I feel like we should make earth:moon ratio as consistent as possible, but the sun:earth can be bent so we don't create a huge scene in three.js. I'm hoping to make the moon look more like a huge solar flare so it's distance isn't as easily noticed.

Given how small the moon is, we might want to have three separate scenes the user can switch over to: Earth focused, Moon focused, and perspective of earth from the moon.

Let me know your thoughts.

**Comment by hdua1** [comment]
You’re right about the moon’s distance from earth being 100x its size, and in no way we can implement that. 

pasted graphic 1

In the above screenshot, it seems like the distance of earth to sun is lesser by only a small number. At this point, I’m not sure if we can relate the orbit radius with the sizing of earth - had the earth size been accurate or even half of the actual size then this distancing and orbiting would be apt.

If you feel orbit distance of 3 in our units is too low, then we can keep it 4 or 5 (since we’re keeping 10K as base). Keeping it 50 would mean 500K miles of radius around earth.

**Comment by trevorforrey** [comment]
I think our model has switched from a hard 10k per unit. As the moon is set to 1/4 the size of earth, and the earth is set to 4, (but its diameter is around 120,000km). I'll switch it back over to 5 and we can ask Joe about it!

**Comment by trevorforrey** [comment]
Talked with Himanshu, and we've agreed to bring this into dev with the intent of improving moon/earth distancing in the future

**Pull request merged**
