### PR TITLE
Containerizing the project

### PR DESCRIPTION
**Pull request by trevorforrey**
Got all packages needed to build the web project. Attempted to do the same for spyce

### CODE REVIEW

**Comment by zawata** [comment]
firstly I didn't know you could do PR Drafts, so thats cool. 

second, rebased on latest dev.

**Comment by zawata** [comment]
rebased again to include Flask server stuff(thought i got it last time.)

docker image mostly rebuilt. now 3 stages with intermediate build files eliminated from the final image. 

currently doesn't run, there's a dependency problem with libboost-system that I'm installing but it still can't be found. didn't have time to figure it out right now.

**Comment by zawata** [comment]
Everything is fixed and working now.

the image is rebased on debian slim to avoid the GlibC vs musl-libc with alpine(detailed in research somewhere)

debian's apt system has to be "updated" before anything can be installed. 
it also contains cmake 3.7(i think) and we need 3.12 minimum so we have to download and install it manually(luckily not hard.)

Also we have to install the dev-versions of the libboost packages otherwise we have to specify package versions.

**Comment by zawata** [comment]
fixed for deployment on heroku. 
http://docker-space.herokuapp.com/index.html

This can be changed to an actual PR and merged. 
Though I don't know how to do that.

**Comment by trevorforrey** [comment]
This PR brings in changes to fully build our project via docker, allowing us to run the full project pipeline (C -> Flask -> Web Page) without having to worry about specific OS issues. 

To Test:

- [ ] Download and Install [Docker](https://www.docker.com/get-started)
Once you have docker installed, _make sure_ that you have the _docker daemon running_

- [ ] **Build the project**
By running the command (inside the project directory): `docker build -t space .`
(This should take a long time the first time you run it)

- [ ] **Run the containerized project**
Run the following command: `docker run -p 5000:5000 space`

- [ ] **Make sure that the project runs**
You should see the webpage at http://localhost:5000

Now whenever you make a code change, you can run the above two commands to test the full pipeline. If only working on frontend code that doesn't rely on the backend, you can still use the same `npm run dev` command.

**Comment by zawata** [comment]
note that if you run into any network issues: i found that adding `--network host` to the build an run commands fixed them.

**Review by dlahtine — APPROVED** [review]
Works for me.

**Comment by trevorforrey** [comment]
Merging in, due to approval from @dlahtine!

**Pull request merged**
