### PR TITLE
Pushed change to SpeedSlider to make slider functionality work

### PR DESCRIPTION
**Pull request by kritikabhat**
Pull request for Speed Slider. Change made to the SpeedSlider.js fille. Requesting review and testing.  Thanks.

### CODE REVIEW

**Review by dlahtine — APPROVED** [review]
Seems to work. Even at 50x, the speed is underwhelming; we should discuss what we want that to look like (maybe make the slider a log scale?) but it's definitely working.

**Comment by zawata** [comment]
The speed should be underwhelming. 30sec * 50x = 15min. ie 2min irl = 1 hour in the sim. 

even outside of the speed, the model only updates once every 30sec. setting the multiplier speed too fast and you'll see the model jump on update. setting the update speed too fast and you'll put strain on the server.
realistically we could preload the times between the current and next upload but the logistics of only returning partial date updates from the object function would be a nightmare.

**Review by trevorforrey — CHANGES_REQUESTED** [review]
From reading the code, it doesn't look like this will increase the speed of the simulation, only the amount of times we request positional data in a given time frame. 

We want the increased speed to relate to how fast the simulation goes.

**Comment by dlahtine** [comment]
> From reading the code, it doesn't look like this will increase the speed of the simulation, only the amount of times we request positional data in a given time frame.
> 
> We want the increased speed to relate to how fast the simulation goes.

I can assure you that that isn't the case. It does indeed cause the simulation time to pass by faster. Back when I was polling for the simulation time, I could see the time increasing much faster with this code in place. It doesn't increase the amount of requests made; that is handled by the web/config/config.js file, which is not a part of these changes.

**Comment by dlahtine** [comment]
> The speed should be underwhelming. 30sec * 50x = 15min. ie 2min irl = 1 hour in the sim.
> 
> even outside of the speed, the model only updates once every 30sec. setting the multiplier speed too fast and you'll see the model jump on update. setting the update speed too fast and you'll put strain on the server.
> realistically we could preload the times between the current and next upload but the logistics of only returning partial date updates from the object function would be a nightmare.

I've seen it in action. at x50 speeeds, you get 25 minute jumps. It's visible, but It's still difficult to see. I have a video of it if you want me to DM it to you.

**Comment by trevorforrey** [comment]
My bad! I believe you. I’d love to see it though, could you dm it to me?

**Comment by trevorforrey** [comment]
Feel free to merge in then!!

**Pull request merged**
