### PR TITLE
Solar visual

### PR DESCRIPTION
**Pull request by kritikabhat**
Can you please review.

### CODE REVIEW

**Review by trevorforrey — CHANGES_REQUESTED** [review]
Looking good!

Is there anyway we can make the non-sun light stuff darker? Maybe by removing some other lights?

screen shot 2019-02-13 at 8 23 54 pm


The earth looks like it's still lit from the non-sun facing side

**Comment by kritikabhat** [comment]
> Looking good!
> 
> Is there anyway we can make the non-sun light stuff darker? Maybe by removing some other lights?
> 
> screen shot 2019-02-13 at 8 23 54 pm
> 
> The earth looks like it's still lit from the non-sun facing side

I actually removed all the other lights except the hemiLight (as they made the scene look blotchy.) I am assuming that when Earth passes in front of sun- the hemiLight also falls on the Earth (because the light is actually not coming from the sun- it just looks like it is), and that is why it looks like it is also getting light. It is not possible to remove this. 
I will take another look at it in the upcoming sprints when we can see Earth clearly again. I will research this.

**Comment by trevorforrey** [comment]
screen shot 2019-02-15 at 11 56 54 am

Bringing sun in and it looks great. Resizing works as well, great job!!

**Comment by trevorforrey** [comment]
Also, 2k earth texture looks really nice!

**Review by trevorforrey — APPROVED** [review]

**Pull request merged**
