### PR TITLE
Moon View Functionality

### PR DESCRIPTION
**Pull request by trevorforrey**
Added moon view functionality. You can click the button to toggle between the two views.

Screen Shot 2019-04-14 at 2 56 54 PM

Screen Shot 2019-04-14 at 2 57 11 PM

### CODE REVIEW

**Comment by trevorforrey** [comment]
_Note: A bug we'll need to fix is always having one side of the moon showing the whole time. I'm going to make this another task in Taiga._

**Review by PauloJaime — APPROVED** [review]
It looks good to me when I run on my computer.

**Review by dlahtine — APPROVED** [review]
Works. I don't know if we're going to run into problems with seeing the spacecraft though; might end up behind the moon or something.

**Comment by trevorforrey** [comment]
@dlahtine I totally agree. I think this will serve as the beginning functionality of it. For the next week I'll try implementing another orbit controls camera that starts at the position one would see it from earth.

Here are screenshots of my most recent changes. Nothing in the camera itself, only in where the camera buttons are placed.

Screen Shot 2019-04-18 at 9 20 52 PM

**Pull request merged**
