### PR TITLE
T40 SPK Frame Data

### PR DESCRIPTION
**Pull request by zawata**
Should provide Frame data with respect to epoch time from an Observing Body. 

This requires the Exception PR to be approved and merged first. 

Another PR will be made shortly(tomorrow maybe) to give access to the available epoch time frame for a target.

### CODE REVIEW

**Comment by zawata** [comment]
note to @trevorforrey I need some feedback on the settings. 

I elected to use the J2000 reference frame but we may need the EclipJ2000 frame instead:
https://naif.jpl.nasa.gov/pub/naif/toolkit_docs/Tutorials/pdf/individual_docs/17_frames_and_coordinate_systems.pdf

Also I've elected to prevent any Light-Time Aberration Correction. Any thoughts on this?

**Comment by zawata** [comment]
https://naif.jpl.nasa.gov/pub/naif/toolkit_docs/Tutorials/pdf/individual_docs/17_frames_and_coordinate_systems.pdf

aAlso I've elected to prevent any Light-Time Aberration Correction. Any thoughts on this?

**Comment by dlahtine** [comment]
I don't have material to test this.

**Review by dlahtine — DISMISSED** [review]
spyce library fails to build: recieving error:
```
Scanning dependencies of target spyce
[ 33%] Building CXX object spyce/CMakeFiles/spyce.dir/py_wrapper.cpp.o
/home/david/Documents/Capstone-DeepSpace/S19-Team2/spyce/py_wrapper.cpp: In function ‘void init_module_spyce()’:
/home/david/Documents/Capstone-DeepSpace/S19-Team2/spyce/py_wrapper.cpp:36:53: error: no matching function for call to ‘boost::python::class_<spyce>::staticmethod(const char [10], int (*)(std::__cxx11::string))’
         .staticmethod("str_to_id", &spyce::str_to_id)
                                                     ^
In file included from /usr/include/boost/python.hpp:18:0,
                 from /home/david/Documents/Capstone-DeepSpace/S19-Team2/spyce/py_wrapper.cpp:1:
/usr/include/boost/python/class.hpp:356:11: note: candidate: boost::python::class_<T, X1, X2, X3>::self& boost::python::class_<T, X1, X2, X3>::staticmethod(const char*) [with W = spyce; X1 = boost::python::detail::not_specified; X2 = boost::python::detail::not_specified; X3 = boost::python::detail::not_specified; boost::python::class_<T, X1, X2, X3>::self = boost::python::class_<spyce>]
     self& staticmethod(char const* name)
           ^~~~~~~~~~~~
/usr/include/boost/python/class.hpp:356:11: note:   candidate expects 1 argument, 2 provided
spyce/CMakeFiles/spyce.dir/build.make:65: recipe for target 'spyce/CMakeFiles/spyce.dir/py_wrapper.cpp.o' failed
make[2]: *** [spyce/CMakeFiles/spyce.dir/py_wrapper.cpp.o] Error 1
CMakeFiles/Makefile2:90: recipe for target 'spyce/CMakeFiles/spyce.dir/all' failed
make[1]: *** [spyce/CMakeFiles/spyce.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```
when I run make. Rebuilding, cleaning, etc. and no changes to this error.

**Review by zawata — COMMENTED** [review]
latest commit should fix this

**Review by dlahtine — CHANGES_REQUESTED** [review]
Builds fine now, but I recieve this error when trying to call `get_frame_data(-39, 399, 5.92316e+08)` after loading the full trajectory bsp file:
```
SPICE(NOLOADEDFILES) --
 
At least one SPK file needs to be loaded by SPKLEF before beginning a search.
 
A traceback follows.  The name of the highest level module is first.
spkez_c --> SPKEZ --> SPKGEO --> SPKSFS
 
Oh, by the way:  The SPICELIB error handling actions are USER-TAILORABLE.  You
can choose whether the Toolkit aborts or continues when errors occur, which
error messages to output, and where to send the output.  Please read the ERROR
"Required Reading" file, or see the routines ERRACT, ERRDEV, and ERRPRT.
 
================================================================================
Process finished with exit code 1
```

**Comment by zawata** [comment]
Rebased on latest dev. 

@dlahtine please retest.
note that the current code is technically incorrect as all files need to be added the class with "add_kernel" theres a task to fix the API that i will begin after this is merged.

**Comment by dlahtine** [comment]
Successfully recieved frame data.

**Review by dlahtine — APPROVED** [review]

**Pull request merged**
