### PR TITLE
Adding Solar Flare

### PR DESCRIPTION
**Pull request by trevorforrey**
- Changed sun to solar flare
- Changed Earth's texture so it now is effected by light
- Switched earth to 8k texture

### CODE REVIEW

**Comment by trevorforrey** [comment]
screen shot 2019-02-17 at 2 33 28 pm

**Comment by kritikabhat** [comment]
image

Is that dot the moon?

**Comment by kritikabhat** [comment]
Also, the 8K earth looks amazing. But the 1K bump map ruins it. That map works with a 1k Earth map. That map on top of the high definition map just makes Earth look hazy, so it looks like a low definition earth only. How about we use the elevation map from here: [NASA Earth image repository](https://visibleearth.nasa.gov/view.php?id=73934).
Look at the difference it makes.

**Comment by kritikabhat** [comment]
This looks amazingly realistic @trevorforrey. Absolutely love how good this looks. 
My only concern is that short point where the sun is behind the Earth and so nothing is visible on the screen anymore. Very realistic! 
But if in future, if we want to change this- we could discuss this with Joe and see if he would be okay with 2-3 more stars (like Alpha centauri) so there would always be some light on Earth. 
But I like this. It looks great.

**Comment by trevorforrey** [comment]
@kritikabhat That new texture map really does look amazing! Thanks so much for adding that.

- For the moon, Himanshu is working on sizing and orbit distances, so the size of it may change.
- For the dark side of the earth, I completely agree with you. I don't think we're 100% there, but it's another step closer. It could be nice to have a very light amount of hemisphere lighting on the earth. I've also seen an earth texture of the earth at night. A dream would be to have the daytime texture when the light hits and the night texture on the darkened parts.

**Review by kritikabhat — CHANGES_REQUESTED** [review]
Suggestion:
Let us use a higher definition image for the bump map with the 8k Earth version or either keep the low grade Earth or remove the bump map completely.
We can do one of these. Low def bump map is messing up the 8k Earth.

For future sprint, we could add other stars for background light (if asked by sponsor.)

**Comment by kritikabhat** [comment]
> * working

I added

> @kritikabhat That new texture map really does look amazing! Thanks so much for adding that.
> 
> * For the moon, Himanshu is working on sizing and orbit distances, so the size of it may change.
> * For the dark side of the earth, I completely agree with you. I don't think we're 100% there, but it's another step closer. It could be nice to have a very light amount of hemisphere lighting on the earth. I've also seen an earth texture of the earth at night. A dream would be to have the daytime texture when the light hits and the night texture on the darkened parts.

That image is only in my local. :) I was just trying it out.
A daytime texture and a night texture? That would be truly amazing. There are those Earth maps for "night time" with street lights and they look great. Wouldn't it be great if the other side of Earth could show those night lights half of it would be day-light? 
But this looks so amazing. Really creative use of the lensflare.

**Comment by trevorforrey** [comment]
@kritikabhat That would be the dream earth (half day and half night)

**Review by kritikabhat — APPROVED** [review]

**Pull request merged**
