### PR TITLE
Converting Frontend to React

### PR DESCRIPTION
**Pull request by trevorforrey**
- I refactored the frontend to react so now it is organized by components.

- To Test
- [ ] run `npm install` 
- [ ] start the dev web server
- [ ] make sure it loads and you can maneuver around.

_Note: The moon button only will say "loading" after clicking, the moon scene functionality has not been converted over as it will be changing._

### CODE REVIEW

**Review by hdua1 — CHANGES_REQUESTED** [review]
Good work converting to React, Trevor. I think it's more responsive than the previous version. I found that the Scene Switch button is not working (see screenshot). I looked up the code, statement "I was clicked!" is not getting printed on console either. I'm not sure where you pulled/created the class for switching, but there's some problem in there. Other than that, it works great!

image

**Comment by trevorforrey** [comment]
Works for me. Are you not seeing the following in the console window?

Screen Shot 2019-03-25 at 6 26 36 PM

**Review by kritikabhat — COMMENTED** [review]
The code looks good. Much more compact and elegant!  
The functionality works fine. The only thing I noticed is that the Loading button animation doesn't have a setTimeout in the javascript so the animation never stops right now. Also, if you click it, the "loading" text gets weird sometimes (see attached pic.) 
But we can fix this whenever we add the moon functionality or whatever we want the button to do (as you mentioned we are changing that).

image

So, I think we are good with this code. Just wanted to point out the lack of setTimeout so we remember it. Great work as always Trevor. Thanks so much!

**Review by kritikabhat — APPROVED** [review]
This code is good for merging. 
The loading functionality of button would simply require copy-pasting that code into the JS from CSS, which we can do later when we change the functionality of the button. This should also fix the wonky loading text issue.

**Review by PauloJaime — APPROVED** [review]
The code looks much easier to be understood good. It looks simples!
On my side, the functionalities work fine. good job!

**Pull request merged**
