### PR TITLE
Timeline Slider UI

### PR DESCRIPTION
**Pull request by trevorforrey**
Created the basic UI of the timeline slider (currently does not change the simulation)

Please test to see if it displays properly and let me know of any styling suggestions.

Screen Shot 2019-03-26 at 10 14 39 AM

### CODE REVIEW

**Review by kritikabhat — APPROVED** [review]
Looks good. I think we are good to merge.
I think we are good to merge this. 
image

**Comment by trevorforrey** [comment]
Thanks! I'm making a small update to have a button that shows/hides the controls on the bottom. Once that's in I'll ask for another quick look and then merge if approved.

**Review by hdua1 — APPROVED** [review]
Works well for me!

**Review by kritikabhat — APPROVED** [review]

**Comment by trevorforrey** [comment]
Added a show/hide controls button

Screen Shot 2019-03-27 at 7 11 39 PM

**Pull request merged**
